### ISSUE TITLE
merged获取到的是data优先覆盖answers?

### ISSUE THREAD

**Issue by seekwe** [saojs/kopy#8]
https://github.com/saojs/kopy/blob/c86ef1f074f116e4473c0a46729c979b546c34c6/src/index.js#L50

**Comment by egoist** [comment]
data 是你提供的 answers 是用户输入的所以我觉得应该是 data 可以覆盖 answers.

**Comment by seekwe** [comment]
有个奇怪的问题,比如有个选项a用户(answers)输入是1,代码预设是(data)是2,那么最终复制的文件模板里<%= a%>则是2,这属于正常?

**Comment by seekwe** [comment]
最后看代码用templateOptions去处理了一次,不知道是否与你本意冲突 :)

**Comment by egoist** [comment]
data 就是用来给 template 提供除了 answers 之外的变量的，data 不是 answers 的默认的 😅

**Comment by seekwe** [comment]
如果template里要用到用户输入的就不行?
